name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker Login
      run: docker login -u hemanthad23 -p "akonpopStar@143"

    - name: Set up Docker Auth Config
      run: echo '$DOCKER_AUTH_CONFIG' > /tmp/docker-auth.json
      env:
        DOCKER_AUTH_CONFIG: $(cat docker-auth.json)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker buildx create --use
        docker buildx build --tag hemanthad23/portfolio_testing --push . --auth docker-auth-config=/tmp/docker-auth.json
